### ISSUE TITLE
Unable to get icon from scrapping GPlay Store web page

### ISSUE THREAD

**Issue by pnu-s** [Exodus-Privacy/exodus-core#14]
The following line does not work anymore because the class "covert-image" was apparently removed from the image.

https://github.com/Exodus-Privacy/exodus-core/blob/f20384135085c892e8f0983120f3db68a6782f1f/exodus_core/analysis/static_analysis.py#L315

This can cause issues and make Exodus unable to scan some applications (in case the first 2 methods of getting the icon failed).

**Comment by counter-reverse** [comment]
It is the source of the other issue here: https://github.com/Exodus-Privacy/exodus-core/issues/8 I have just to wait for the agreement for my pull request.

I have already fixed that here: https://github.com/Exodus-Privacy/exodus-core/pull/15.

**Comment by pnu-s** [comment]
Thanks @counter-reverse I'll take a look at your PR

**Comment by pnu-s** [comment]
Fixed in v1.0.16, waiting for integration into exodus

**Comment by pnu-s** [comment]
This was fixed but Google changed their class name again. :(
@Gu1nness got the idea to use the filter alt = "Cover art" instead and it seems to work, we need to do that now.

**Comment by pnu-s** [comment]
Fixed in v1.0.17
