### ISSUE TITLE
currently use dexdump to analyze apk files

### ISSUE THREAD

**Issue by counter-reverse** [Exodus-Privacy/exodus-core#16]
For the moment the core of exodus embeds dexdump to perform analysis.

This choice makes exodus louder in term of space on the disk, less flexible and makes also the code less maintainable.

So I suggest to replace the usage of dexdump by code that perform analysis. The choice of the library to use is a great question. I let you give your opinion on this issue.

When we will find a good library, I will be ready to contribute to include it into exodus privacy.

Good luck to choose the library.

**Comment by pnu-s** [comment]
dexdump is the tool provided by the Android project for this purpose.

I agree that the implementation is not very readable and maintainable (possibly could be improved) but at this moment we do not plan to replace this tool (especially if we don't have any replacement idea).
For now I'll close this issue.
