### ISSUE TITLE
Detect if dexdump is not available

### ISSUE THREAD

**Issue by Rudloff** [Exodus-Privacy/exodus-core#17]
Hello,

In v2.0.2, if dexdump is not installed, `detect_trackers()` simply returns an empty list.
I think it should raise an exception instead, because the current behavior can be confusing.

**Comment by counter-reverse** [comment]
In my opinion the best to do is to remove entirely dexdump from the core of exodus privacy and then recode it in python. You can check this issue: https://github.com/Exodus-Privacy/exodus-core/issues/16.

I keep in mind that detect like you want might be faster.

**Comment by burkhardtc** [comment]
@Rudloff
You are right.

@counter-reverse
I disagree. In my opinion I would prefer to solve the requirements systemwide by using the distribution package management.

<pre>
apt install dexdump androguard python3-cryptography python3-jellyfish python3-traitlets python3-future python3-cffi python3-urllib3 python3-idna python3-decorator python3-ipython-genutils python3-pexpect python3-pycparser python3-pil python3-pip python3-setuptools python3-chardet python3-requests python3-certifi
</pre>

**Comment by pnu-s** [comment]
This has been solved in the meantime, the script will fail if dexdump cannot be found.
