### ISSUE TITLE
zoom App - Unable to compute APK fingerprint

### ISSUE THREAD

**Issue by tiemes** [Exodus-Privacy/exodus-core#36]
I'm not able to start a new analysis using this app: https://play.google.com/store/apps/details?id=us.zoom.videomeetings 

reported "unable to compute APK fingerprint": https://reports.exodus-privacy.eu.org/en/analysis/208285/

In times like these with the discussion about privacy, it would be essential to be able to scan this app.

**Comment by pnu-s** [comment]
Hi @tiemes 

Thanks for reporting this.
We had reports up to the version 4.5 but for some reasons exodus was not able to scan the newest versions.

I made a hotfix to correct this, you now have the latest version scanned: https://reports.exodus-privacy.eu.org/fr/reports/122599/

I'll make the change properly in exodus-core later this week

**Comment by pnu-s** [comment]
For the record and in case I forget, the problematic line is here:
https://github.com/Exodus-Privacy/exodus-core/blob/v1/exodus_core/analysis/static_analysis.py#L363

**Comment by pnu-s** [comment]
Forgot to close this, but it's fixed properly in 405ad4b8ea570ec61f2b996a918097161c87e51f
