### ISSUE TITLE
Use GitHub Actions to create release with tar file

### ISSUE THREAD

**Issue by pnu-s** [Exodus-Privacy/exodus-core#57]
We used to have Travis CI to push our generated tar archive to 2 places:
* pypi
* github releases

We now have github actions to push to pypi (the most important) but it does not do the same for github releases.

**Comment by Jean-BaptisteC** [comment]
I think is complicate, maybe download release on pypi to add on github releases. But we can have a conflict because we have 2 files with same name on github releases.

**Comment by Jean-BaptisteC** [comment]
Done with https://github.com/Exodus-Privacy/exodus-core/commit/8e3023cbafbffd927ff3eaf67a0ed2eb0f92dfeb
