### ISSUE TITLE
Update GitHub actions to only push new version to pypi once

### ISSUE THREAD

**Issue by pnu-s** [Exodus-Privacy/exodus-core#62]
Currently, when pushing a new tag, GitHub actions tries to push the new version to pypi twice, once for each python version currently supported.

There is no real impact, except for the pipeline to fail.

We should make sure to only push it with one version of python.

**Comment by Jean-BaptisteC** [comment]
You can create [dependent jobs](https://docs.github.com/en/actions/using-workflows/advanced-workflow-features) to publish package only one time if build job sucess.
